### ISSUE TITLE
Some refinement suggestions

### ISSUE THREAD

**Issue by eclarke12** [eadorin/about-face#1]
```js
/**
     * returns a Token object given an id
     * @param tokenId   the <id> of the token to retrieve.
     * @return Token
     */
    static getTokenByTokenID(tokenId)
    {
        return TokenLayer.instance.objects.children.find(token => token.data._id == tokenId);
    }
```
could just be `canvas.tokens.get(tokenId)` (ie. there's no need for you to define a new method here)

this:
```js
// rotate the token
        let t = AboutFace.getTokenByTokenID(token._id);
        t.data.rotation = rotationValue;
        t.rotate({angle:rotationValue,snap:45});
        t.refresh();
```
is unneccessary. If you update the data of the token correctly and `await` it then the canvas token should rotate also. if not, something else going on maybe.

I would also recommend putting some kind of guard clause in your update handler so it only executes when the update has facing information.

finally, I suggest looking at preUpdate hooks down the road, as you could save a DB operation (currently your module fires on token update and calls token update)

Overall, great module, can't wait to see it in action!

**Comment by eadorin** [comment]
@eclarke12 I tried 3 different ways to rotate the token. setting `data.rotation` was my first attempt but the canvas never seemed to update.. I may take another stab at it.

I didn't know about  `canvas.tokens.get(tokenId)` ... oops!

good call on having facing information.

I was originally using preUpdate but sometimes it seemed like it wasn't getting the information quickly enough (and caused issues with clients). Having said that, I reworked some code after changing it that may very well let preUpdate work again. I'll give it a shot! Thanks for the feedback!

**Comment by eclarke12** [comment]
If you update token data and await it, it should correctly update the canvas. But I haven't messed with rotation so I'm speaking hypothetically.

Doing pre updates can be finnicky, and if you are only sending one extra DB operation in an update hook it's not the end of the world. just be careful about recursive loops.

GLHF!

**Comment by edzillion** [comment]
closed as these fixes have been implemented. rotation is via update like so:

```js
        token.data.rotation = dir;
        token.update({
            rotation: dir
        });
```
