### ISSUE TITLE
Token Vision does not apply on first direction change using arrows

### ISSUE THREAD

**Issue by Norc** [eadorin/about-face#10]
Token vision is not updated correctly on the first arrow move, even though the token changes facing correctly. only after the second consecutive arrow press in the same direction is the vision corrected. This happens when turning in any direction.

For instance, this token has a 270 angle of vision, and was heading left. I then hit the down arrow. The "blind spot" in the token's vision is still "behind" it from its previous orientation:

![image](https://user-images.githubusercontent.com/64667579/85951920-2f3a2880-b934-11ea-8b17-99ef14290541.png)

when I then hit the down arrow again, the vision is finally corrected:

![image](https://user-images.githubusercontent.com/64667579/85951862-e4201580-b933-11ea-95e2-74be09f82995.png)

About Face 1.6 is the only module enabled, Foundry 0.64 and DND 0.93.

**Comment by p4535992** [comment]
Just a gif example o the issue
![example](https://i.imgur.com/K0jxMBh.gif)

**Comment by eadorin** [comment]
I had only been using 360 degree vision which is why I didn't catch this. I'll investigate!

**Comment by Norc** [comment]
This is FIXED in the latest stealth release! much appreciated, I can use the module again ahha
