### ISSUE TITLE
Adding a new token to a scene with Indicators enabled requires a canvas redraw

### ISSUE THREAD

**Issue by BlitzKraig** [eadorin/about-face#11]
Indicators do not appear, and rotation does not work, until the canvas is redrawn. (`canvas.draw()` or change scenes)

This can be fixed without requiring a redraw:

```
export class AboutFace
{
...
  
  static async onCreateToken(scene,token) {
        let ti = await TokenIndicator.init(canvas.tokens.placeables.filter(tokenPlaceable => tokenPlaceable.id == token._id)[0]);
        ti.create(game.settings.get(mod,"indicator-sprite"));
        if (!useIndicator || useIndicator == "1") {
            ti.hide();
        }
        TokenIndicators.push(ti);
    }

...
}
...

Hooks.on('createToken', AboutFace.onCreateToken);
```

I'd be happy to submit a PR with these changes, though you may wish to refactor to your taste.

**Comment by eadorin** [comment]
@BlitzKraig Dude. THANK YOU. I had halfway solved it but not 100%. Thank you!

**Comment by BlitzKraig** [comment]
Hey, no problem! Sorry for closing, I was trying to work out how to clear up my GitHub app. Looking forward to the update!
