### ISSUE TITLE
Manual rotation not possible

### ISSUE THREAD

**Issue by M0nk3yy** [eadorin/about-face#25]
Hi,

The readme states: "Hold SHIFT and using your W,A,S,D or ↑,←,↓,→ you can change the direction your token is facing without moving" and this was always what I experienced until recently.

Is this a bug or is manual rotation no longer supported functionality? Even with "Enable About Face Rotation" unchecked, manual rotation only sets tokens as south-facing.

**Comment by TomChristoffer** [comment]
Several actions seem to reset rotation to south-facing, and the manual rotation does indeed seem to be broken

**Comment by eadorin** [comment]
This is the bug I'm actively working to fix. The updateToken is firing twice, probably because of some jank code I wrote. The second firing resets the position to 0.
