### ISSUE TITLE
About Face throws error and does not function for tokens not placed while About Face is active

### ISSUE THREAD

**Issue by Norc** [eadorin/about-face#29]
If a token is not placed while the module is active, the following error is thrown and rotation does not work:

![image](https://user-images.githubusercontent.com/64667579/94209847-46d56e80-fe9b-11ea-8f56-fe97f890caab.png)

This particularly an issue for prepackaged content such as Clash at Kobold Cauldron. 

Try testing with that world (5e 0.96) Reproduced in both 0.6.6 and 0.72.

**Comment by edzillion** [comment]
Token flags are now set on `createToken` which fixed this issue and maybe the linked one too.
