### ISSUE TITLE
Moving in straight lines with mouse causes token to point in wrong direction

### ISSUE THREAD

**Issue by Norc** [eadorin/about-face#30]
If you move using the arrow keys, the token points in the direction expected. However, if you go straight up, down, left, or right by  by mouse, the token will always be pointing at a 45 degree angle instead of straight in the direction moved.

Try testing with that world (5e 0.96) Reproduced in both 0.6.6 and 0.72 on Clash at Kobold Cauldron world.

**Comment by edzillion** [comment]
This has been fixed it seems. If you can reproduce on the latest I will reopen thanks.
