### ISSUE TITLE
Turning on Direction Indicators does not function for tokens not placed when About Face was active

### ISSUE THREAD

**Issue by Norc** [eadorin/about-face#31]
similar to #29 , if you have pre-existing tokens in your map, then try to set Arrow Indicators to Always, the following error displays and the arrows are not added:

![image](https://user-images.githubusercontent.com/64667579/94212218-94ed7080-fea1-11ea-9a27-9940e9e7343b.png)

Tested with both 0.6.6 and 0.72 on Kobold Cauldron world, 5E 0.96.

**Comment by edzillion** [comment]
This is fixed in latest (the package manager hasn't been updated yet but you can use the module.json) can you test?
