### ISSUE TITLE
Cannot Read Property Owner

### ISSUE THREAD

**Issue by KonteiKeisei** [eadorin/about-face#36]
`Uncaught (in promise) TypeError: Cannot read property 'owner' of undefined
    at new TokenIndicator (token-indicator.js:15)
    at Function.init (token-indicator.js:28)
    at createTokenHandler (about-face.js:421)
    at Function._call (foundry.js:2426)
    at Function.callAll (foundry.js:2386)
    at Function._handleCreateEmbeddedEntity (foundry.js:29508)
    at Function._handleCreateEmbeddedEntity (foundry.js:33778)
    at Scene.createEmbeddedEntity (foundry.js:29479)
TokenIndicator @ token-indicator.js:15
init @ token-indicator.js:28
createTokenHandler @ about-face.js:421
_call @ foundry.js:2426
callAll @ foundry.js:2386
_handleCreateEmbeddedEntity @ foundry.js:29508
_handleCreateEmbeddedEntity @ foundry.js:33778
createEmbeddedEntity @ foundry.js:29479
async function (async)
createEmbeddedEntity @ foundry.js:29469
(anonymous) @ multilevel.js:732
Promise.then (async)
_execute @ multilevel.js:732
batched @ multilevel.js:752
Promise.finally (async)
_queueAsync @ multilevel.js:765
refreshAll @ multilevel.js:1444
_onUpdateScene @ multilevel.js:1481
_call @ foundry.js:2426
callAll @ foundry.js:2386
(anonymous) @ foundry.js:29230
_handleUpdate @ foundry.js:29222
update @ foundry.js:29203
async function (async)
update @ foundry.js:29195
update @ foundry.js:29278
update @ foundry.js:33655
unsetFlag @ foundry.js:29862
controlTokenEventHandler @ target-enhancements.js:433
async function (async)
controlTokenEventHandler @ target-enhancements.js:408
_call @ foundry.js:2426
callAll @ foundry.js:2386
control @ foundry.js:11407
_onClickLeft @ foundry.js:11636
_onClickLeft @ foundry.js:44646
callback @ foundry.js:35797
_handleClickLeft @ foundry.js:35982
_handleMouseDown @ foundry.js:35962
a.emit @ index.js:181
r.dispatchEvent @ InteractionManager.ts:1106
r.processPointerDown @ InteractionManager.ts:1307
t.recursiveFindHit @ TreeSearch.ts:173
t.recursiveFindHit @ TreeSearch.ts:113
t.recursiveFindHit @ TreeSearch.ts:113
t.recursiveFindHit @ TreeSearch.ts:113
t.findHit @ TreeSearch.ts:200
r.processInteractive @ InteractionManager.ts:1177
r.onPointerDown @ InteractionManager.ts:1252
`

**Comment by edzillion** [comment]
Hi @KonteiKeisei thanks for the report. Can you test w latest and see if the issue still exists?
