### ISSUE TITLE
Sight Layer Depreciation

### ISSUE THREAD

**Issue by KonteiKeisei** [eadorin/about-face#37]
`SightLayer#updateToken() is deprecated in favor of Token#updateSource()
updateToken @ foundry.js:39065
updateTokenEventHandler @ about-face.js:328
_call @ foundry.js:2426
call @ foundry.js:2411
(anonymous) @ foundry.js:29591
updateEmbeddedEntity @ foundry.js:29578
updateMany @ foundry.js:12233
moveMany @ foundry.js:12175
_handleMovement @ foundry.js:2981
(anonymous) @ foundry.js:2950
setTimeout (async)
_onMovement @ foundry.js:2950
_handleKeys @ foundry.js:2727
_onKeyDown @ foundry.js:2682
`

`

  | update | @ | foundry.js:39054
-- | -- | -- | --
  | setAlphas | @ | RoofsLayer.js:214
  | _onUpdateToken | @ | RoofsLayer.js:155
  | _call | @ | foundry.js:2426
  | callAll | @ | foundry.js:2386
  | _handleUpdateEmbeddedEntity | @ | foundry.js:29647
  | _handleUpdateEmbeddedEntity | @ | foundry.js:33793
  | updateEmbeddedEntity | @ | foundry.js:29615
  | async function (async) |   |  
  | updateEmbeddedEntity | @ | foundry.js:29605
  | updateMany | @ | foundry.js:12233
  | moveMany | @ | foundry.js:12175
  | _handleMovement | @ | foundry.js:2981
  | (anonymous) | @ | foundry.js:2950
  | setTimeout (async) |   |  
  | _onMovement | @ | foundry.js:2950
  | _handleKeys | @ | foundry.js:2727
  | _onKeyDown | @ | foundry.js:2682

`

`You are calling the SightLayer#update method which has been renamed to SightLayer#refresh to be consistent with other PIXI objects.
update @ foundry.js:39054
setAlphas @ RoofsLayer.js:214
_onUpdateToken @ RoofsLayer.js:155
_call @ foundry.js:2426
callAll @ foundry.js:2386
_handleUpdateEmbeddedEntity @ foundry.js:29647
_handleUpdateEmbeddedEntity @ foundry.js:33793
updateEmbeddedEntity @ foundry.js:29615
async function (async)
updateEmbeddedEntity @ foundry.js:29605
updateMany @ foundry.js:12233
moveMany @ foundry.js:12175
_handleMovement @ foundry.js:2981
(anonymous) @ foundry.js:2950
setTimeout (async)
_onMovement @ foundry.js:2950
_handleKeys @ foundry.js:2727
_onKeyDown @ foundry.js:2682
`

**Comment by edzillion** [comment]
Fixed in `v1.7.0`
