### ISSUE TITLE
ActorIsPC Deprecated

### ISSUE THREAD

**Issue by KonteiKeisei** [eadorin/about-face#38]
`The Actor#isPC attribute has been deprecated in favor of the more general Entity#hasPlayerOwner attribute

get isPC | @ | foundry.js:30791
-- | -- | --
  | generateDefaultIndicator | @ | token-indicator.js:88
  | create | @ | token-indicator.js:205
  | getIndicator | @ | about-face.js:106
  | async function (async) |   |  
  | getIndicator | @ | about-face.js:105
  | ready | @ | about-face.js:94
  | _call | @ | foundry.js:2426
  | call | @ | foundry.js:2411
  | draw | @ | foundry.js:10032
  | async function (async) |   |  
  | draw | @ | foundry.js:10012
  | onChange | @ | foundry.js:6828
  | _update | @ | foundry.js:3425
  | set | @ | foundry.js:3407
  | _updateObject | @ | foundry.js:24651
  | async function (async) |   |  
  | _updateObject | @ | foundry.js:24651
  | _onSubmit | @ | foundry.js:5177

`

**Comment by edzillion** [comment]
Fixed in #34
