### ISSUE TITLE
Issue with updating and installing

### ISSUE THREAD

**Issue by NukeMaster0** [eadorin/about-face#41]
I keep getting this issue whenever I try to update and install this module.
![image](https://user-images.githubusercontent.com/68701755/99806348-eb76d400-2b0b-11eb-885c-0a6d32013d8f.png)

**Comment by edzillion** [comment]
That's strange. How are you updating? There was a short window when that file was missing (yesterday between ~9-10GMT) but it is now there:

[https://raw.githubusercontent.com/eadorin/about-face/master/module.json](https://raw.githubusercontent.com/eadorin/about-face/master/module.json)

I just tried installing via the Install Module -> filter packages route and it worked fine.

**Comment by NukeMaster0** [comment]
I just hit "check update" and it gave me that. Weird... Either way, a lot of people are having the same issue on discord as well.

**Comment by NukeMaster0** [comment]
![image](https://user-images.githubusercontent.com/68701755/99826396-4a494700-2b26-11eb-83e2-3abd0aadb08c.png)
![image](https://user-images.githubusercontent.com/68701755/99826460-6816ac00-2b26-11eb-8d50-f5a932c612c9.png)
Found some, it's not just you, many other modules are having this issue and I emailed the Devs for Foundry and they said-

"Hi there!

Looks like the calendar-weather manifest isn't pointing to a valid manifest. I'll let the dev know via our community discord. You may need to uninstall this module and reinstall it.

Cheers,
SM
Foundry Support"

I have like 76 modules and I can't bear to tell everyone but I did tell them that most modules are like this and they have to let every Module dev know what they have to do.
What sucks is that when I uninstalled this and went to reinstalled this module it did not install what so ever, wish this was in core lol.

**Comment by NukeMaster0** [comment]
UPDATE:

The issue went away on its own, most likely the Devs at Foundry fixed this issue, though there are still some modules (1 right now for me anyway) with the same issue, I can hopefully say that this issue, on this module, can be closed, sadly I don't know what caused it or how to fix it though... Thank you.

**Comment by edzillion** [comment]
Hey thanks for keeping on top of this @NukeMaster0 glad to hear it resolved itself.
