### ISSUE TITLE
Can't delete or move some creatures after duplication

### ISSUE THREAD

**Issue by MisterHims** [eadorin/about-face#43]
Hello! A big thank you for this module which I appreciate very much.

However, I'm having an issue when using macros that duplicate creatures. Some are impossible to delete or move until I refresh.

In the first example given, the Summon macro is used (https://pastebin.com/R4bMHZkk) with the following active modules: The Furnace, DAE, Midi-QOL and About Face

In the second example, another macro is used (https://pastebin.com/FGzufS3i) with the following active modules: The Furnace, Item Macro and About Face

No apparent error in the console, and for information I am using Foundry VTT in version 0.7.6

![qlJMIVJut3](https://user-images.githubusercontent.com/41004451/100589355-47eba780-32f3-11eb-9b79-5037ae7511ac.gif)
![ZZRNjIYFt6](https://user-images.githubusercontent.com/41004451/100589360-4ae69800-32f3-11eb-98eb-b29b1c11b2b0.gif)

**Comment by edzillion** [comment]
Thanks for the report. Can you test in latest? I am not sure it will be fixed but I made such major changes that I am interested to see what will happen.

**Comment by MisterHims** [comment]
Hello! Indeed, I no longer encounter this error since the last update. We can say that this issue has been resolved. Thank you :)
