### ISSUE TITLE
Deactive debug traces

### ISSUE THREAD

**Issue by DarKDinDoN** [eadorin/about-face#6]
Hello,

Thx for that module. It's really helpful!
Could you deactivate the debug traces in the console? It makes really hard to read and debug in Foundry when this module is activated.

**Comment by Dumbhuman** [comment]
I'd very much like to second this request.  The debug spam from HoverToken is a little overwhelming though strangely I have one token that doesn't get errors from that function, but when I copy/paste that same token the duplicates do get that error.  I suspect maybe you left the debugging in to try to root out that behavior.

Regardless, it would be helpful to be able to deactivate all debug tracing as DarKDinDoN suggested.

![AboutFaceHoverTokenError](https://user-images.githubusercontent.com/63615591/85752890-a49dc300-b6c0-11ea-9f80-1f723da3fe31.gif)
