### ISSUE TITLE
Attribute bar is being hidden by token when moving

### ISSUE THREAD

**Issue by DarKDinDoN** [eadorin/about-face#7]
Hi,

When moving the token around, at some point the attribute is behind the token making it hard to read.

![image](https://user-images.githubusercontent.com/1687854/85339356-46b48400-b4e4-11ea-8ebf-2c5b450f5ae1.png)

On the left, the token hasn't been moved. On the right the token has been moved around. (using arrow keys)

**Comment by edzillion** [comment]
This has been fixed, at least I can't reproduce. Tell me if it still exists in v1.7.0 and I will reopen
