### ISSUE TITLE
Arrows in Token HUD gone?

### ISSUE THREAD

**Issue by zarazandra** [eadorin/about-face#86]
Hi there, 
I am not sure, if you have anything to do with it, but before some time I had arrows in my Token HUD (not Token Action HUD!), with which I could rotate the tokens without moving it in 8 directions. But since some time (can't name it really), this feature is gone and I just wanted to ask, if you removed it OR I just missed a setting OR if that is from some other module I may have ditched in the past. 

I really miss this feature :| 

Have a nice new year!

![Screenshot 2024-01-04 144135](https://github.com/eadorin/about-face/assets/70195103/eb4cd94e-4220-43a4-a416-9903821920e2)
![Screenshot 2024-01-04 144135_altered](https://github.com/eadorin/about-face/assets/70195103/4fcd0faf-3613-44c2-9dc1-cfae02591646)

**Comment by eadorin** [comment]
This was a feature of the original code. Holding `shift` would allow you to change directions. I am no longer maintaining this project, though.  I was the original author, but it moved on: https://github.com/League-of-Foundry-Developers/about-face/tree/master

**Comment by zarazandra** [comment]
Thanks for the info!
