### ISSUE TITLE
Many console errors on startup, depending on settings configuration

### ISSUE THREAD

**Issue by Norc** [eadorin/about-face#9]
I'm running Foundry 0.64, 0.93 DND5E, no other modules active. Logged in as a GM on a map without a background image set.

The functionality of About Face seems to work fine, but I get two errors in the console on startup with the following settings:

![image](https://user-images.githubusercontent.com/64667579/85951451-4592b500-b931-11ea-97ee-069ee01d72e5.png)

However, if I turn off the Token indicators, there is a hundred errors or so on startup. Note that these errors only appear if About Face is enabled and still appear if it's the only module:

![image](https://user-images.githubusercontent.com/64667579/85951669-b71f3300-b932-11ea-91d7-813ba290898f.png)

All of the remaining several screens of errors are the "cannot read property "hide" of undefined" error with those settings.

**Comment by rinnocenti** [comment]
here with others modules install I get error on mousehover tokens.
![image](https://user-images.githubusercontent.com/3178127/86147647-051d6d80-bad0-11ea-8d30-d8a352d71401.png)
end not show direction icon.

**Comment by rinnocenti** [comment]
I now uninstalled and installed and the error disappeared, I don't know if there is, but it would be interesting a warning to reinstall the module

**Comment by Norc** [comment]
Discussed with you, but this is definitely not fixed, sadly...
